<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<STYLE type="text/css">
	table {border-collapse: collapse;}
	table td {padding: 0px}
</STYLE>
</head>
<body>
<div style="position:absolute;top:10.13in;left:0.55in;width:0.92in;line-height:0.11in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">DECLARATION</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:10.27in;left:0.55in;width:7.73in;line-height:0.11in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">In consideration of payment of the premium, TUNE Insurance Malaysia Berhad agrees to provide insurance for the Insured Person(s) according</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:10.43in;left:0.55in;width:5.27in;line-height:0.11in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">to the terms, conditions and exceptions of the Master Policy No. </span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"><?= $masterPolicyCode ?></span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> attached.</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:11.78in;left:0.54in;width:1.16in;line-height:0.11in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">Authorised Signatory</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:11.92in;left:0.54in;width:2.20in;line-height:0.11in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">CEO, TUNE Insurance Malaysia Berhad</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:12.11in;left:0.54in;width:1.48in;line-height:0.11in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">Account Code : <?= $accountCode ?></span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:12.24in;left:0.54in;width:1.32in;line-height:0.11in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">Issue Date : <?=date('d/m/Y',strtotime($policy->Created))?></span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:11.72in;left:0.50in;width:3.34in;height:0.02in" src="<?=base_url()?>assets/images/ci_1.png" />
<div style="position:absolute;top:5.26in;left:0.75in;width:0.24in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">No</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.26in;left:2.80in;width:0.64in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Helvetica;color:#000000">Benefits</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.26in;left:5.35in;width:1.20in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Helvetica;color:#000000">Limt Per Person</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.26in;left:7.48in;width:0.70in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Helvetica;color:#000000">Standard</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.53in;left:0.75in;width:0.13in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">1</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.70in;left:0.75in;width:0.13in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">2</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.53in;left:1.23in;width:3.49in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Accidental Death &amp; Permanent Disablement (Adult)</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.70in;left:1.23in;width:3.49in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Accidental Death &amp; Permanent Disablement (Child)</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.53in;left:5.63in;width:0.65in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Per adult</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.70in;left:5.64in;width:0.63in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Per child</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.53in;left:7.58in;width:0.51in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">75,000</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.70in;left:7.58in;width:0.51in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">15,000</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.96in;left:0.75in;width:0.26in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">3(i)</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.96in;left:1.23in;width:2.53in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Helvetica;color:#000000">Medical Expenses due to Accident</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.96in;left:7.58in;width:0.51in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">10,000</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.22in;left:0.75in;width:0.29in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">3(ii)</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.22in;left:1.23in;width:2.54in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Helvetica;color:#000000">Medical Expenses due to Sickness</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.22in;left:5.43in;width:1.04in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Per adult/ child</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.22in;left:7.62in;width:0.42in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">2,500</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.48in;left:0.75in;width:0.33in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">3(iii)</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.48in;left:1.23in;width:1.42in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Compassionate Visit</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.48in;left:7.25in;width:1.15in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">NOT COVERED</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.75in;left:0.75in;width:0.13in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">4</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.75in;left:1.23in;width:1.30in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Helvetica;color:#000000"><u>Personal Liability</u></span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:6.87in;left:1.23in;width:1.25in;height:0.01in" src="<?=base_url()?>assets/images/ci_2.png" />
<div style="position:absolute;top:6.75in;left:7.58in;width:0.51in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">50,000</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.02in;left:0.75in;width:0.13in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">5</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.02in;left:1.23in;width:1.18in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Helvetica;color:#000000"><u>Inconveniences</u></span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.19in;left:1.23in;width:1.18in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Trip Cancellation</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.36in;left:1.23in;width:1.12in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Trip Curtailment</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.52in;left:1.23in;width:1.24in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Missed Departure</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.69in;left:1.23in;width:0.89in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Travel Delay</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.86in;left:1.23in;width:1.04in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Travel Reroute</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.19in;left:5.43in;width:1.04in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Per adult/ child</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.69in;left:5.43in;width:1.04in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Per adult/ child</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.86in;left:5.43in;width:1.04in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Per adult/ child</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.19in;left:7.62in;width:0.42in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">1,000</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.36in;left:7.25in;width:1.15in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">NOT COVERED</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.52in;left:7.25in;width:1.15in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">NOT COVERED</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.69in;left:7.68in;width:0.29in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">400</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.86in;left:7.68in;width:0.29in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">150</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.18in;left:1.23in;width:0.66in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Helvetica;color:#000000"><u>LOSSES</u></span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.35in;left:1.23in;width:3.72in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Damage to Luggage During Air common Carrier Travel</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.52in;left:1.23in;width:1.06in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Luggage Delay</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.69in;left:1.23in;width:3.17in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Snatch Theft ( Ground Only ) for the following :</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.86in;left:1.23in;width:1.84in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">1) Loss of Personal Money</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.03in;left:1.23in;width:1.90in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">2) Loss of Travel Document</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.20in;left:1.23in;width:1.85in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">3) Loss of Personal Effects</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.86in;left:5.43in;width:1.04in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Per adult/ child</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.03in;left:5.43in;width:1.04in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Per adult/ child</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.20in;left:5.43in;width:1.04in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Per adult/ child</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.86in;left:7.68in;width:0.29in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">500</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.03in;left:7.48in;width:0.70in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Up to 300</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.20in;left:7.68in;width:0.29in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">500</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.57in;left:1.23in;width:2.62in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">PREMIUM PER PAX FOR 1-15 DAYS</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.57in;left:5.36in;width:1.20in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Exclude 6% GST</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.57in;left:7.61in;width:0.45in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">RM15</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.82in;left:1.23in;width:2.70in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">PREMIUM PER PAX FOR 16-30 DAYS</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.82in;left:5.36in;width:1.20in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Exclude 6% GST</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.82in;left:7.61in;width:0.45in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">RM25</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:5.20in;left:0.72in;width:8.03in;height:4.82in" src="<?=base_url()?>assets/images/ci_5.png" />
<div style="position:absolute;top:4.94in;left:0.75in;width:1.97in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">SUMMARY OF COVERAGE</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.18in;left:3.73in;width:2.20in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Helvetica;color:#000000">TUNE INBOUND PA PROTECTOR</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.33in;left:3.83in;width:2.01in;line-height:0.13in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Helvetica;color:#000000">CERTIFICATE OF INSURANCE</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.58in;left:0.54in;width:1.08in;line-height:0.10in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">IMPORTANT NOTICE</span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.76in;left:0.54in;width:0.12in;line-height:0.10in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">1.</span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.76in;left:0.72in;width:5.36in;line-height:0.10in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">This certificate together with proof of purchase/bills/documentary evidence must be produced in the event of claim</span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.96in;left:0.54in;width:0.12in;line-height:0.10in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">2.</span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.96in;left:0.72in;width:6.41in;line-height:0.10in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">Please notify TUNE Insurance Malaysia Berhad, Level 9, Wisma Tune No.19 Lorong Dungun Damansara Heights, 50490 Kuala Lumpur</span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.08in;left:0.72in;width:8.41in;line-height:0.10in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">(Attn: Travel Claims Tel No. 603- 2087 9000 Fax No.603-2094 1366 immediately in writing in event of a claim. Any claims notification should be notified not later than 30 days from</span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.20in;left:0.72in;width:1.63in;line-height:0.10in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">the date of the claims occurrence)</span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.43in;left:0.54in;width:0.12in;line-height:0.10in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">3.</span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.43in;left:0.72in;width:4.01in;line-height:0.10in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">Any extension of cover is not allowed during the trip on or after coverage is enforced.</span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.64in;left:0.54in;width:0.12in;line-height:0.10in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">4.</span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.64in;left:0.72in;width:7.22in;line-height:0.10in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">In the event of a claim, the insured has to provide a copy of his passport, the visa and the air ticket to prove that he/she travels within the date of this visa.</span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.56in;left:0.54in;width:1.82in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Master Policyholder Name</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.56in;left:2.52in;width:0.08in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">:</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.56in;left:2.73in;width:1.25in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"><?= $policy->Name ?></span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.56in;left:5.20in;width:1.45in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Policy/Certificate No:</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.56in;left:6.90in;width:0.08in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">:</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.56in;left:7.11in;width:2.15in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"><?= $masterPolicyCode.'#<br>'.$policy->InsuranceCode ?></span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.81in;left:0.54in;width:1.23in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Master Policy No:</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.81in;left:2.52in;width:0.08in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">:</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.81in;left:2.73in;width:1.29in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"><?= $masterPolicyCode ?></span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:2.05in;left:0.54in;width:1.53in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Valid ID/ Passport No:</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:2.05in;left:2.52in;width:0.08in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">:</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:2.05in;left:2.73in;width:1.25in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"><?= $policy->IDNumber ?></span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:2.31in;left:0.54in;width:0.81in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Issue Date:</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:2.31in;left:2.52in;width:0.08in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">:</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:2.31in;left:2.73in;width:0.80in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"><?=date('d/m/Y',strtotime($policy->Created))?></span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:2.54in;left:0.54in;width:0.77in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Plan Type:</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:2.54in;left:2.52in;width:0.08in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">:</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:2.56in;left:2.73in;width:2.03in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"><?= $policy->ProductID == 1 ? "PLATINUM" : "STANDARD" ?> </span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ABCDEE+Calibri;color:#000000">(15days/30days)</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ABCDEE+Calibri;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:2.74in;left:2.73in;width:6.40in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Helvetica;color:#000000">The departure date shall be not later than 90 days from the date of approval of visa in line with the validity</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:2.89in;left:2.73in;width:0.70in;line-height:0.13in;"><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Helvetica;color:#000000">of the visa.</span><span style="font-style:normal;font-weight:normal;font-size:9pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.15in;left:0.54in;width:0.99in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Travel Period:</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.15in;left:2.52in;width:0.08in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">:</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.15in;left:2.73in;width:6.30in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">The period of insurance shall be effective from the date of departure of the Insured by flight to</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.32in;left:2.73in;width:2.89in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000">Malaysia and covered for max 15/30 days.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:10.72in;left:0.51in;" src="<?=base_url()?>assets/images/ri_1.png" />
<div style="position:absolute;top:0.21in;left:3.10in;width:3.13in;line-height:0.12in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Helvetica;color:#000000">TUNE INSURANCE MALAYSIA BERHAD</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000">(30686-K)</span><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.36in;left:2.39in;width:4.53in;line-height:0.11in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">Head Office :Tune Insurance Malaysia Berhad, Level 9 Wisma Tune, No. 19 Lorong</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.49in;left:2.98in;width:3.37in;line-height:0.11in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">Dungun, Damansara Heights, 50490 Kuala Lumpur, Malaysia.</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.63in;left:3.14in;width:3.03in;line-height:0.11in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">Tel No:</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> +603-20879000  </span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">Fax No:</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> +603-20941366         </span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.77in;left:3.80in;width:1.74in;line-height:0.11in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">Website:</span><a href="http://www.tuneprotect.com" style="text-decoration: none;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> www.tuneprotect.com</span></a>
<span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:0.00in;left:1.09in;width:1.23in;height:1.07in" src="<?=base_url()?>assets/images/ri_2.png" />
</body>
</html>
